### ISSUE TITLE
Beneficiarios de "nuevo conocimiento"

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#10]
en el campo "Regiones" del "Ámbito de aplicación" de la pantalla "Beneficiarios" al dar de alta un "Nuevo Conocimiento" que se permita elegir como buleano todas las provincias, Comunidades autonomas y paises

![image](https://user-images.githubusercontent.com/49024845/55168976-33492a80-5174-11e9-8a4a-3c9470cf48e0.png)

**Comment by jlagunapkf** [comment]
¿Deben de existir una opción en el desplegable de cada una de las siguientes?

- Todas provincias
- Todas comunidades
- Todos paises

O bien un check debejo del desplegalbe de regiones donde se marque 
Todo/as provincias, comunidades y paises

**Comment by JaimeInncome** [comment]
Debe ser un único desplegable con todas las opciones
- "España"
- "Bilateral España +..."
-  "UE"
-  "UE + países asociados"
-  "Otros"
-  CCAA y dentro de cada una sus provincias. Ej:
     - Extremadura
            - Badajoz
            - Cáceres
     - Galicia
             - A Coruña
             - ....

**Comment by jlagunapkf** [comment]
Esa opción para nada es usable, es decir, no puede aparecer en un único desplegable más de 60 items. En este caso, no sería mejor una entrada de texto?

**Comment by JaimeInncome** [comment]
Se tiene que poder filtrar por las regiones, de ahí que tengan que ser valores únicos, si se os ocurre otra opción que no sea un campo abierto adelante.

**Comment by jlagunapkf** [comment]
Lo podemos hacer como se hace en la administración de equipos. Para seleccionar un nuevo miembro del equipo, se debe introducir un texto y que se muestren las posibles opciones. De estas, seleccionar una.

**Comment by JaimeInncome** [comment]
me aprece bien así

**Comment by JaimeInncome** [comment]
en los que la CCAA se llama igual que una provincia poner "Com. Madrid" "Reg Murcia" "Com Valenciana"... ¿me podéis pasar un listado con los campos que habéis añadido aquí?

Gracias

**Comment by solegarcia** [comment]
provincias = ['Álava', 'Albacete', 'Alicante', 'Almería', 'Asturias', 'Ávila', 'Badajoz', 'Barcelona', 'Burgos', 'Cáceres',
    'Cádiz', 'Cantabria', 'Castellón', 'Ciudad Real', 'Córdoba', 'La Coruña', 'Cuenca', 'Gerona', 'Granada', 'Guadalajara',
    'Guipúzcoa', 'Huelva', 'Huesca', 'Islas Baleares', 'Jaén', 'León', 'Lérida', 'Lugo', 'Madrid', 'Málaga', 'Murcia',
    'Orense', 'Palencia', 'Las Palmas', 'Pontevedra', 'La Rioja', 'Salamanca', 'Segovia', 'Sevilla', 'Soria', 'Tarragona',
    'Santa Cruz de Tenerife', 'Teruel', 'Toledo', 'Valencia', 'Valladolid', 'Vizcaya', 'Zamora', 'Zaragoza'];

  comunidades = ['Andalucía', 'Aragón', 'Canarias', 'Cantabria', 'Castilla y León', 'Castilla-La Mancha', 'Cataluña', 'Ceuta',
    'Comunidad Valencia', 'Comunidad de Madrid', 'Extremadura', 'Galicia', 'Islas Baleares', 'La Rioja', 'Melilla', 'Navarra',
    'País Vasco', 'Principado de Asturias', 'Región de Murcia'];

  otros = ['España', 'Bilateral España', 'UE', 'UE + Países Asociados', 'Otros'];
