### ISSUE TITLE
Modo visualización convocatorias

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#11]
A la hora de entrar en un "Conocimiento" (que se debería llamar "convocatoria") ya creado, se debería acceder en modo de visualización y en el menú opciones que aparezcan las posibles acciones:
- Editar (solo para personal con permisos para ello)
- Eliminar (solo para personal con permisos para ello)
- Imprimir
- Crear un proyecto de esta convocatoria (y que se abra la pantalla de crear nuevo proyecto con la plantilla de la convocatoria o elegir entre la plantillas disponibles. Me decís la mejor manera para hacer esto porque puede ser complicado)

**Comment by JaimeInncome** [comment]
Además, al entrar a consultar una convocatoria debería verse toda la información en una única pantalla y cuando se entra al modo edición permita editar campos concretos y guardar el cambio sin tener que recorrer todo el proceso

**Comment by jlagunapkf** [comment]
Entiendo que las convocatorias las podrán ver todos los usuarios de la aplicación?

**Comment by JaimeInncome** [comment]
si, las pueden ver todos, pero editarlas solo unos pocos.
