### ISSUE TITLE
Códigos de nuevos proyectos

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#13]
Al dar de alta un "nuevo proyecto" ver cómo se define el código para que coincida con lo que se crea ahora en Navision. Intentar que sea lo más automático posible para evitar errores

**Comment by jlagunapkf** [comment]
En la anterior reunión, comentamos que el proyecto iba a contener un código que estaba formado por 
Código cliente (Este código tendría un código de socio con el cual estaría relacionado)
Código Autoincremental. (Pendiente de confirmar)

¿Cómo lo hacemos?

**Comment by JaimeInncome** [comment]
olvidaos de esto, porque con los últimos cambios no hay muchos socios, y es mejor hacerlo según el excel que os pasé que reflejaba la clasificación de navision con algunos añadidos
