### ISSUE TITLE
Cambio campos "Nuevo proyecto"

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#14]
En la pantalla de alta de "nuevo proyecto" cambiar los campos:

- [x] - "Nombre" por "Título"

- [x] - "Estado actual": que las opciones disponibles en este momento sean "Identificado" o "Preparación"

**Comment by jlagunapkf** [comment]
Cada plantilla puede tener unos estados diferentes por lo que no se debería predefinir ni filtrar los estados.

**Comment by JaimeInncome** [comment]
pero cuando se empieza un proyecto siempre es por alguno de esos estados. todo está bastante cerrado ya.
