### ISSUE TITLE
Pantalla beneficiarios en nuevo conocimiento

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#15]
A la hora de modificar los "beneficiarios" de un "Nuevo conocimiento":

- [x] - Incluir la opción de marcar "Sectores de actividad no incluidos" y que sea el mismo campo que el de "Sectores de actividad"

- [x] - A la hora de filtrar pos texto en los CNAE (sector de actividad) no encuentra a no ser que pongas el texto exacto y aquí

   - por un lado la caja para escribir es muy reducida
   - sería mejor si encontrara todos los resultados que contienen lo que se escribe y no sea tan limitante

- [x] - En "Sector industrial" si solo hay doce opciones que se vean todas porque ahora mismo solo se muestran 10 y parece que no hay más

![image](https://user-images.githubusercontent.com/49024845/55171214-39d9a100-5178-11e9-967b-849e624825b6.png)

**Comment by jlagunapkf** [comment]
En los sectores de actividad no incluidos, si se marca esto, se entiende que todos los demás sectores van a estar incluidos?? O se pueden marcar unos como incluidos y otros como no incluidos?

**Comment by JaimeInncome** [comment]
Así es, cuando se marcan unos no incluidos el resto estarán incluidos. pero cuando se indiquen unos no incluidos, la información que queremos que aparezca es la de no incluidos.

**Comment by jlagunapkf** [comment]
Por ello, en vez de crear otro elemento o listado de sectores no incluidos, mi opción es crear un check, que cuando se marque, en el listado de sectores de actividad se verán los sectores no incluidos y cuando no esté marcado la referencia sera a los incluidos.  ¿Qué te parece?

**Comment by JaimeInncome** [comment]
me parece bien la opción.
Gracias!
