### ISSUE TITLE
orden INCENTIVOS / conocimiento

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#33]
Al acceder al actual conocimiento (que se deberá llamar incentivos" los elementos aparecerán por "fecha de fin de presentación solicitudes" de más próximo a más lejano y luego las cerradas

**Comment by jlagunapkf** [comment]
¿A qué te refieres con las cerradas?

**Comment by JaimeInncome** [comment]
Los incentivos tienen un plazo de solicitud, si el plazo de solicitud está vigente, decimos que están abiertas, y una vez pasado ese plazo las convocatorias cierran y no se pueden abrir nuevos proyectos para esa convocatoria
Acabo de caer que creo que no estamos contemplando en ningún sitio. 
Cuando se ven todas las convocatorias, se debería identificar cuáles están abiertas y cuales cerradas. Quizás se pueda hacer algo automático si cuando la fecha indicada en "Fecha fin presentación de solicitudes" ya ha pasado y que también se pueda marcar una casilla de "cerrada" para cuando depende de un presupuesto

**Comment by jlagunapkf** [comment]
Podríamos crear un campo boolean que se marque automáticamente como cerrado cuando la fecha actual sea posterior a la fecha de fin de solicitudes.

**Comment by JaimeInncome** [comment]
me parece bien, siempre que cuando se modifique manualmente responda.
