### ISSUE TITLE
Cambios tipo de empresas

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#35]
Al dar de alta un nuevo incentivo (actual conocimiento) en Beneficiarios,

- [x] Cambiar "Tipo empresa" por "Tipo de entidad" y añadir:

- Midcaps
- Organismos de investigación públicos (Unis, CI)
- Organismos de investigación privados (Unis, CT)

- [x] Quitar de la lista "Universidades" y "Centros Tecnológicos"

- [x] Lo mismo en Volumen de la ayuda

- [x] Añadirlo en la api

![image](https://user-images.githubusercontent.com/49024845/55336239-e8455500-549c-11e9-84e4-14fe87b779e9.png)

**Comment by jlagunapkf** [comment]
A parte del tipo de empresa donde aparecen tanto centros tecnológicos como universidades, en el apartado de características de la financiación -> volumen de la ayuda, aparecen los valores mínimos, máximos y una explicación para los centros tecnológicos y universidades.

¿Qué hacemos en este caso?

**Comment by JaimeInncome** [comment]
cambiarlos ahí también para que quede igual en los dos sitios
