### ISSUE TITLE
estados de proyecto

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#41]
Al crear los estados se tienen que dar los estados predefinidos , no se tiene que dar la opción de crear estados libres

![image](https://user-images.githubusercontent.com/49024845/55338218-7d961880-54a0-11e9-9e5b-debe1468d6a6.png)

**Comment by jlagunapkf** [comment]
Como hemos hablado, tendríamos una serie de estados predefinidos. Que serían los siguientes.

- Identificado
- Preparación
- Presentado
- No presentado
- Aprobado
- Denegado
- Ejecución
- Finalizado
- Cerrado
- Certificación
- Certificado
- Emisión MIV
- Renunciado
- Requerimientos

Para cada incentivo, se van a seleccionar uno o varios de los anteriores.
