### ISSUE TITLE
campo pequeño

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#56]
El campo "nombre" de la entidad "Organismo" es pequeño, que entren más caracteres

![image](https://user-images.githubusercontent.com/49024845/56906470-9515f080-6aa2-11e9-8ebd-40e7a9862ab5.png)

**Comment by jlagunapkf** [comment]
Actualmente el campo está limitado a 50 caracteres. Lo voy a limitar a 150 caracteres. ¿Como lo ves? @JaimeInncome

**Comment by JaimeInncome** [comment]
lo veo bien.
