### ISSUE TITLE
cambio de equipos

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#58]
No deja añadir gente a un equipo al darle al + en Usuario

![image](https://user-images.githubusercontent.com/49024845/56955101-bc22ff80-6b40-11e9-91e7-ce5fb7902a79.png)

**Comment by jlagunapkf** [comment]
Tienes que seleccionar un elemento del desplegable que se muestra cuando escribes el nombre del usuario.

**Comment by JaimeInncome** [comment]
El tema es que no se abre ningún desplegable

**Comment by JaimeInncome** [comment]
olvídalo, resuelto
