### ISSUE TITLE
Establecer Códigos

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#59]
En Códigos para proyectos, ampliar el campo para que sea  de unos 25 caracteres, sera abierto

En Códigos para tareas e hitos, para que quede como comentamos en la reunión referido a las alertas, en primer lugar cambiaría el título del campo para no confundir y lo llamaría "Tipo", y serían los siguientes:
- Presentar
- Justificar
- Dar respuesta
- Facturar
- Otras gestiones

**Comment by jlagunapkf** [comment]
Por los tipos solo serían de las tareas ¿no?

**Comment by JaimeInncome** [comment]
si si, esos tipos serían solo para las tareas y los hitos

**Comment by jlagunapkf** [comment]
En la reunión, lo que hablamos fue que se iba a asignar un tipo de tarea a cada tarea para de esta manera poder realizar el envío de notificaciones a los usuarios a partir de este tipo de tarea. Pero los hitos dijimos que se quedaban como estaban, ¿No estoy en lo cierto?

**Comment by JaimeInncome** [comment]
¿pero los hitos no tienen alertas? ¿no se puede hacer con ellos lo mismo? también tendremos que saber cuando acaba un hito

**Comment by jlagunapkf** [comment]
Pero los hitos también van a ser del tipo: 

- Presentar
- Justificar
- Dar respuesta
- Facturar
- Otras gestiones

¿Tiene sentido que los hitos y las tareas tengan el mismo tipo? Dalo una vuelta y me comentas.

**Comment by jlagunapkf** [comment]
Las alertas de finalización de un hito, llegarán a todos los miembros que participan en el proyecto.

**Comment by JaimeInncome** [comment]
si, los hitos tendrán los mismos y te hago modificaciones, ya revisado con MAría y Cruz, serían los siguientes:
- Presentar
- Justificar
- Requerimientos
- Modificaciones
- Alegaciones
- Otras tareas

**Comment by JaimeInncome** [comment]
Si, llegarán a todos
Y sobre esto, María (perfil socio) deberá ver todas las tareas e hitos de todos, esto es así, ¿verdad?

**Comment by jlagunapkf** [comment]
Para ello deberéis de incluir a María en todos los proyectos como participante, con el perfil socio.
