### ISSUE TITLE
hitos y tareas desordenados

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#60]
cuando se crea un proyecto, luego los hitos y las tareas aparecen desordenados, deberían aparecer en el mismo orden en que se crean

![image](https://user-images.githubusercontent.com/49024845/56955996-22108680-6b43-11e9-9a3a-c53e43fce128.png)

**Comment by jlagunapkf** [comment]
Esto lo más coherente no sería que se ordenaran por fecha de fin?

**Comment by JaimeInncome** [comment]
vale si, acabo de ver el otro apartado donde aparecen, pero si no tienen fecha ninguno, ¿Cómo se ordenan?

**Comment by jlagunapkf** [comment]
No tienen ordenación predefinida. Solamente está ordenado por fecha.

**Comment by jlagunapkf** [comment]
Si todas las fechas de las tareas del proyecto están sin completar, todas las tareas se ordenaran por el orden del estado sino, se ordenarán por fecha de fin.
