### ISSUE TITLE
campos de Hito

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#61]
Necesitamos revisar los campos que se muestran en los Hitos, hay información que es del proyecto, no de cada hito y que se vaya repitiendo.

Además de que había información de las deducciones fiscales que me aparece en proyectos de ayudas. Si te parece el lunes me bajo y lo vemos como está todo organizado para que quede donde debe

![image](https://user-images.githubusercontent.com/49024845/56956659-158d2d80-6b45-11e9-89c6-5cb79bedf66b.png)

**Comment by jlagunapkf** [comment]
Inicialmente se iba a incluir en incentivos, pero en la reunión acordamos incluirlo en el Hito.

Las fechas que me has subrayado son fecha de inicio de justificación y la segunda es fecha de fin de justificación y el más información es sobre la justificación también.

![image](https://user-images.githubusercontent.com/40607175/56957891-e4aef780-6b48-11e9-9bf0-d5fa66b1568c.png)

**Comment by jlagunapkf** [comment]
Y los dos checks aparecen como campos del hito en la ficha de deducción fiscal

![image](https://user-images.githubusercontent.com/40607175/56958057-6b63d480-6b49-11e9-8a6c-4dedb1071c8a.png)
