### ISSUE TITLE
IMPORTANTE: cambiar listado "tipología" en INCENTIVO

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#79]
Al dar de alta los incentivos cambiar el listado de "Tipología" y que sean:

10 - Ayuda nacional de algún Ministerio
11 - Ayuda CDTI
12 - Otras ayudas nacionales
13 - Ayuda regional
14 - Ayuda europea
20 - Deducción fiscal por certificadora
21 - Deducción fiscal por autoliquidación
22 - Deducción fiscal foral
23 - Deducción fiscal por tax lease
30 - Bonificación por certificadora
31 - Bonificación por autoliquidación
40 - Plan de financiación
41 - Otros
50 - Trabajos internos

![image](https://user-images.githubusercontent.com/49024845/62516519-9d11c900-b825-11e9-81a9-9383617d90fc.png)

**Comment by jlagunapkf** [comment]
Me tienes que pasar una relación entre los que están y los nuevos, para saber por cual tengo que cambiar los actuales.
