### ISSUE TITLE
Equipo no volcado en Navision

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#86]
Hemos dado de alta un proyecto en InnHome y al entrar en navision no aparece la gente en el equipo y se han imputado horas y tampoco aparecen en el time report

![image](https://user-images.githubusercontent.com/49024845/62539224-00ffb600-b855-11e9-8d88-f361b3622e9d.png)

**Comment by jlagunapkf** [comment]
Los equipos de trabajo en ningún momento se vuelcan a navision, la gestión de equipos de trabajo se hace sobre la base de datos de la aplicación

Lo que me podrías mirar es si se registran las horas en navision, en el time report no hemos podido realizar pruebas porque no tenemos acceso. Pero inicialmente, mira a ver si se han registrado las horas en el proyecto de navision.

**Comment by JaimeInncome** [comment]
no se vuelcan en navision y en el time report tampoco se refleja
