### ISSUE TITLE
Faltan incentivos a la hora de crear plantillas

### ISSUE THREAD

**Issue by JaimeInncome** [PKFEric/WebInncome#89]
Al ir a crear las plantillas y querer seleccionar el Incentivo al que se quiere asociar, no aparecen todos los incentivos creados

![image](https://user-images.githubusercontent.com/49024845/62620612-138ff300-b91a-11e9-9660-d69caddde413.png)

**Comment by jlagunapkf** [comment]
En lo que quedamos, es que para dar de alta una plantilla, únicamente se pudieran seleccionar aquellos incentivos que estuvieran en estado abierto.

**Comment by JaimeInncome** [comment]
si, pero hay convocatorias que están abiertas y aún así no aparecen
